import Head from 'next/head'

import Categories from './components/Categories'
import PostCard from './components/PostCard'
import PostWidget from './components/PostWidget'
import {getPosts} from "../services/index"


export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {
      posts.map((post) =>
       <PostCard post={post} key={post.title} />
    )
    }
    <div className='row'>
    <div className='col-8'>
      <PostWidget />
    </div>
    <div className='col-4'>
      <Categories />
    </div>
    </div>
    </>
  )
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}