import Head from 'next/head'

import Categories from '../components/Categories'
import PostCard from '../components/PostCard'
import PostWidget from '../components/PostWidget'
import Navbar from '../components/Navbar'

const posts = [
  {
    title: "Learning Java Script ", excerpt: "LEarning Java by practing daily"
  },
  {
    title: "Learning Java Script ", excerpt: "LEarning Java by practing daily"
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar />

    {
      posts.map((post) =>
       <PostCard post={post} key={post.title} />
    )
    }
    <PostWidget />
    <Categories />
    </>
  )
}
